[project]
name = "uncertainty_cfs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "carla",
    "causalgraphicalmodels>=0.0.4",
    "dice-ml>=0.9",
    "jupyterlab>=4.4.3",
    "lime>=0.2.0.1",
    "matplotlib>=3.10.3",
    "numpy<2",
    "pandas>=2.2.3",
    "pre-commit>=4.2.0",
    "probly>=0.1.0",
    "pyyaml>=6.0.2",
    "recourse>=1.0.0",
    "scikit-learn>=1.6.1",
    "setuptools>=80.9.0",
    "split>=0.4",
    "tensorflow>=2.14.0",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "xgboost>=3.0.2",
]

authors = [
    { name = "Santo Thies", email = "S.Thies@campus.lmu.de" },
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["uncertainty_cfs"]

[tool.uv.workspace]
members = [
    "CARLA",
]

[tool.uv.sources]
carla = { workspace = true }
